Feat/Added boolean allow photo field
tihlde/API pull request #128
Opened 2020-09-11 12:34 UTC by Tobbi-T

# Feat/Added boolean allow photo field
## Added a boolean field allow_photo to user_event.
Link to Trello task: ...

Comments/issues:
Migrations were not made. Should I do it here, or are you doing it in dev?

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ x] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ x] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-09-11 13:12 UTC, Eirsteir requested changes
Nice work Tobias 😄 

Regarding the migrations: 
You can safely delete both files, rebase onto dev (which has the 0007_autoxx file) and then make the migration file again. 

Migrations are a direct moderation of the database schema which means that you can migrate all you want locally and it will not have any effect on the db in dev/prod. These are migrated automatically in those environments. 
The important part is that you add the migrations file, which you have done 😉

2020-09-11 13:12 UTC, Eirsteir commented on app/content/models/user_event.py
> +    allow_photo = models.BooleanField(default=False)
This should be default to True, since the user would actively decide not to allow photos being taken of them 😉

2020-09-11 15:46 UTC, Eirsteir requested changes
Nice 😄 
Please pull the changes from dev into your branch and then add your new migration file (run "make makemigrations") and change the filename to something meaningful.

2020-09-12 19:46 UTC, Zenjjim approved these changes
Enkel og elegant løsning! Bra jobbet @Tobbi-T :D

2020-09-14 14:58 UTC, Eirsteir approved these changes
Clean implementation, nicely done 😄

2020-09-14 14:59 UTC, merged