Chore(refactored userevent)
tihlde/API pull request #143
Opened 2020-09-21 15:48 UTC by Omjoa001

# Refactored UserEvent
## Changed all instances of UserEvent to Registration and user_event to registration
Link to Trello task: ...

Comments/issues:

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ x] PR name is descriptive
- [ ] The PR includes the link to the relevant Trello task
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

- [ x] `python manage.py runserver` was run locally witout errors

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ x ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2020-09-22 19:47 UTC, Eirsteir requested changes
Well done Omar! 😄 This change is long overdue, good work.

I see you have some conflicts that needs to be resolved before this PR can be approved. We can work on this together during the next meeting if you'd like, or you can give it a try yourself by referring to the __git-flow__ document on Drive.

2020-09-22 19:47 UTC, Eirsteir commented on app/content/models/registration.py
>      event = models.ForeignKey('Event', on_delete=models.CASCADE)
Please add the argument `related_name="registrations"` as it would facilitate accessing the registrations from an event.

2020-09-29 07:16 UTC, Zenjjim commented
Nå er du nødt til å kjøre `make format` og `make check`

2020-10-07 06:55 UTC, Eirsteir approved these changes
Nicely done Omer 😄

2020-10-07 15:11 UTC, merged